In [57]:
#Importing Libraries
import streamlit as st
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [58]:
#Loading and Exploring the Dataset
df = pd.read_csv("survey_results_public(2023).csv")

In [59]:
"""from ydata_profiling  import ProfileReport
profile = ProfileReport(df,title="Developer Salary 2023 Report",minimal=True)
profile.to_notebook_iframe()"""

'from ydata_profiling  import ProfileReport\nprofile = ProfileReport(df,title="Developer Salary 2023 Report",minimal=True)\nprofile.to_notebook_iframe()'

In [60]:
"""profile.to_file("Developer_Salary_Report.html")"""

'profile.to_file("Developer_Salary_Report.html")'

In [61]:
unique_countries = df['Country'].unique()
print("Unique Countries:", unique_countries)

Unique Countries: [nan 'United States of America' 'Philippines'
 'United Kingdom of Great Britain and Northern Ireland' 'Finland' 'India'
 'Australia' 'Netherlands' 'Germany' 'Sweden' 'France' 'Albania' 'Nigeria'
 'Spain' 'South Africa' 'Belgium' 'Italy' 'Brazil' 'Portugal' 'Bangladesh'
 'Canada' 'Argentina' 'Switzerland' 'Sri Lanka' 'Poland' 'Lebanon'
 'Lithuania' 'Serbia' 'Cyprus' 'China' 'Bahrain'
 'Iran, Islamic Republic of...' 'Pakistan' 'Egypt' 'Russian Federation'
 'Turkey' 'Slovakia' 'Latvia' 'Greece' 'Austria' 'Denmark' 'Israel'
 'Norway' 'Hungary' 'Singapore' 'United Arab Emirates' 'Croatia'
 'Czech Republic' 'Kosovo' 'Nepal' 'Slovenia' 'Romania' 'Luxembourg'
 'Indonesia' 'Tunisia' 'Republic of Korea' 'Viet Nam' 'Ukraine' 'Kenya'
 'Nomadic' 'Dominican Republic' 'Morocco' 'Uzbekistan' 'Belarus'
 'Isle of Man' 'Estonia' 'Bulgaria'
 'The former Yugoslav Republic of Macedonia' 'Georgia' 'Ireland' 'Benin'
 'Qatar' 'Japan' 'Venezuela, Bolivarian Republic of...' 'Tajikistan'
 'Malta

In [62]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 89184 entries, 0 to 89183
Data columns (total 84 columns):
 #   Column                               Non-Null Count  Dtype  
---  ------                               --------------  -----  
 0   ResponseId                           89184 non-null  int64  
 1   Q120                                 89184 non-null  object 
 2   MainBranch                           89184 non-null  object 
 3   Age                                  89184 non-null  object 
 4   Employment                           87898 non-null  object 
 5   RemoteWork                           73810 non-null  object 
 6   CodingActivities                     73764 non-null  object 
 7   EdLevel                              87973 non-null  object 
 8   LearnCode                            87663 non-null  object 
 9   LearnCodeOnline                      70084 non-null  object 
 10  LearnCodeCoursesCert                 37076 non-null  object 
 11  YearsCode                   

In [63]:
df.columns

Index(['ResponseId', 'Q120', 'MainBranch', 'Age', 'Employment', 'RemoteWork',
       'CodingActivities', 'EdLevel', 'LearnCode', 'LearnCodeOnline',
       'LearnCodeCoursesCert', 'YearsCode', 'YearsCodePro', 'DevType',
       'OrgSize', 'PurchaseInfluence', 'TechList', 'BuyNewTool', 'Country',
       'Currency', 'CompTotal', 'LanguageHaveWorkedWith',
       'LanguageWantToWorkWith', 'DatabaseHaveWorkedWith',
       'DatabaseWantToWorkWith', 'PlatformHaveWorkedWith',
       'PlatformWantToWorkWith', 'WebframeHaveWorkedWith',
       'WebframeWantToWorkWith', 'MiscTechHaveWorkedWith',
       'MiscTechWantToWorkWith', 'ToolsTechHaveWorkedWith',
       'ToolsTechWantToWorkWith', 'NEWCollabToolsHaveWorkedWith',
       'NEWCollabToolsWantToWorkWith', 'OpSysPersonal use',
       'OpSysProfessional use', 'OfficeStackAsyncHaveWorkedWith',
       'OfficeStackAsyncWantToWorkWith', 'OfficeStackSyncHaveWorkedWith',
       'OfficeStackSyncWantToWorkWith', 'AISearchHaveWorkedWith',
       'AISearchWan

In [64]:
df.isnull().sum()

ResponseId                 0
Q120                       0
MainBranch                 0
Age                        0
Employment              1286
                       ...  
ProfessionalTech       47401
Industry               52410
SurveyLength            2699
SurveyEase              2630
ConvertedCompYearly    41165
Length: 84, dtype: int64

In [65]:
df.describe()

ResponseId     CompTotal       WorkExp  ConvertedCompYearly
count  89184.000000  4.822500e+04  43579.000000         4.801900e+04
mean   44592.500000  1.036807e+42     11.405126         1.031101e+05
std    25745.347541  2.276847e+44      9.051989         6.814188e+05
min        1.000000  0.000000e+00      0.000000         1.000000e+00
25%    22296.750000  6.300000e+04      5.000000         4.390700e+04
50%    44592.500000  1.150000e+05      9.000000         7.496300e+04
75%    66888.250000  2.300000e+05     16.000000         1.216410e+05
max    89184.000000  5.000000e+46     50.000000         7.435143e+07

In [66]:
df = df[["Country", "EdLevel", "YearsCodePro", "Employment", "ConvertedCompYearly"]]
df = df.rename({"ConvertedCompYearly": "Salary"}, axis=1)
df.head()

Country                                       EdLevel  \
0                       NaN                                           NaN   
1  United States of America  Bachelor’s degree (B.A., B.S., B.Eng., etc.)   
2  United States of America  Bachelor’s degree (B.A., B.S., B.Eng., etc.)   
3  United States of America  Bachelor’s degree (B.A., B.S., B.Eng., etc.)   
4               Philippines  Bachelor’s degree (B.A., B.S., B.Eng., etc.)   

  YearsCodePro                                         Employment    Salary  
0          NaN                                                NaN       NaN  
1            9                                Employed, full-time  285000.0  
2           23                                Employed, full-time  250000.0  
3            7                                Employed, full-time  156000.0  
4            4  Employed, full-time;Independent contractor, fr...   23456.0

In [67]:
df = df[df["Salary"].notnull()]
df.head()

Country  \
1                           United States of America   
2                           United States of America   
3                           United States of America   
4                                        Philippines   
5  United Kingdom of Great Britain and Northern I...   

                                             EdLevel YearsCodePro  \
1       Bachelor’s degree (B.A., B.S., B.Eng., etc.)            9   
2       Bachelor’s degree (B.A., B.S., B.Eng., etc.)           23   
3       Bachelor’s degree (B.A., B.S., B.Eng., etc.)            7   
4       Bachelor’s degree (B.A., B.S., B.Eng., etc.)            4   
5  Some college/university study without earning ...           21   

                                          Employment    Salary  
1                                Employed, full-time  285000.0  
2                                Employed, full-time  250000.0  
3                                Employed, full-time  156000.0  
4  Employed, full-time;Independent contractor, fr...   23456.0  
5                                Employed, full-time   96828.0

In [68]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 48019 entries, 1 to 89171
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   Country       48019 non-null  object 
 1   EdLevel       48019 non-null  object 
 2   YearsCodePro  47825 non-null  object 
 3   Employment    48007 non-null  object 
 4   Salary        48019 non-null  float64
dtypes: float64(1), object(4)
memory usage: 2.2+ MB


In [69]:
df = df.dropna()
df.isnull().sum()

Country         0
EdLevel         0
YearsCodePro    0
Employment      0
Salary          0
dtype: int64

In [70]:
df = df[df["Employment"] == "Employed, full-time"]
df = df.drop("Employment", axis=1)
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 39155 entries, 1 to 89171
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   Country       39155 non-null  object 
 1   EdLevel       39155 non-null  object 
 2   YearsCodePro  39155 non-null  object 
 3   Salary        39155 non-null  float64
dtypes: float64(1), object(3)
memory usage: 1.5+ MB


In [71]:
df['Country'].value_counts()

Country
United States of America                                10569
Germany                                                  3201
United Kingdom of Great Britain and Northern Ireland     3072
Canada                                                   1807
India                                                    1600
                                                        ...  
Botswana                                                    1
Sierra Leone                                                1
Guyana                                                      1
Guinea-Bissau                                               1
Antigua and Barbuda                                         1
Name: count, Length: 165, dtype: int64

In [72]:
def shorten_categories(categories, cutoff):
    categorical_map = {}
    for i in range(len(categories)):
        if categories.values[i] >= cutoff:
            categorical_map[categories.index[i]] = categories.index[i]
        else:
            categorical_map[categories.index[i]] = 'Other'
    return categorical_map

In [73]:
country_map = shorten_categories(df.Country.value_counts(), 400)
df['Country'] = df['Country'].map(country_map)
df.Country.value_counts()

Country
United States of America                                10569
Other                                                    9282
Germany                                                  3201
United Kingdom of Great Britain and Northern Ireland     3072
Canada                                                   1807
India                                                    1600
France                                                   1458
Netherlands                                              1002
Australia                                                 985
Brazil                                                    972
Spain                                                     966
Sweden                                                    882
Italy                                                     826
Poland                                                    740
Switzerland                                               511
Denmark                                                   440


In [74]:
fig, ax = plt.subplots(1,1, figsize=(12, 7))
df.boxplot('Salary', 'Country', ax=ax)
plt.suptitle('Salary (US$) v Country')
plt.title('')
plt.ylabel('Salary')
plt.xticks(rotation=90)
plt.show()

C:\Users\bhask\AppData\Local\Temp\ipykernel_19668\1681787070.py:7: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()


In [75]:
df = df[df["Salary"] <= 250000]
df = df[df["Salary"] >= 10000]
df = df[df['Country'] != 'Other']

In [76]:
fig, ax = plt.subplots(1,1, figsize=(12, 7))
df.boxplot('Salary', 'Country', ax=ax)
plt.suptitle('Salary (US$) v Country')
plt.title('')
plt.ylabel('Salary')
plt.xticks(rotation=90)
plt.show()

C:\Users\bhask\AppData\Local\Temp\ipykernel_19668\1681787070.py:7: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()


In [77]:
df["YearsCodePro"].unique()

array(['23', '7', '21', '3', '9', 'Less than 1 year', '10', '2', '6',
       '14', '5', '15', '19', '13', '16', '28', '24', '25', '12', '4',
       '20', '8', '18', '30', '27', '17', '43', '38', '33', '29', '22',
       '1', '11', '34', '42', '26', '31', '36', '39', '40', '32', '44',
       '37', '35', '48', 'More than 50 years', '45', '41', '50', '46',
       '49', '47'], dtype=object)

In [78]:
def clean_experience(x):
    if x ==  'More than 50 years':
        return 50
    if x == 'Less than 1 year':
        return 0.5
    return float(x)

df['YearsCodePro'] = df['YearsCodePro'].apply(clean_experience)

In [79]:
df["EdLevel"].unique()

array(['Bachelor’s degree (B.A., B.S., B.Eng., etc.)',
       'Some college/university study without earning a degree',
       'Master’s degree (M.A., M.S., M.Eng., MBA, etc.)',
       'Professional degree (JD, MD, Ph.D, Ed.D, etc.)',
       'Associate degree (A.A., A.S., etc.)',
       'Secondary school (e.g. American high school, German Realschule or Gymnasium, etc.)',
       'Primary/elementary school', 'Something else'], dtype=object)

In [80]:
def clean_education(x):
    if 'Bachelor’s degree' in x:
        return 'Bachelor’s degree'
    if 'Master’s degree' in x:
        return 'Master’s degree'
    if 'Professional degree' in x or 'Other doctoral' in x:
        return 'Post grad'
    return 'Less than a Bachelors'

df['EdLevel'] = df['EdLevel'].apply(clean_education)

In [81]:
df["EdLevel"].unique()

array(['Bachelor’s degree', 'Less than a Bachelors', 'Master’s degree',
       'Post grad'], dtype=object)

In [82]:
from sklearn.preprocessing import LabelEncoder
le_education = LabelEncoder()
df['EdLevel'] = le_education.fit_transform(df['EdLevel'])
df["EdLevel"].unique()

array([0, 1, 2, 3])

In [83]:
le_country = LabelEncoder()
df['Country'] = le_country.fit_transform(df['Country'])
df["Country"].unique()

array([16, 15,  0,  9,  5, 13,  4, 12,  1,  8,  2, 14,  6, 10,  3,  7, 11])

In [84]:
X = df.drop("Salary", axis=1)
y = df["Salary"]

## #Building and Training the Model


In [85]:
#Linear Regression Model
from sklearn.linear_model import LinearRegression
linear_reg = LinearRegression()
linear_reg.fit(X,y.values)

LinearRegression()

In [86]:
y_pred = linear_reg.predict(X)

In [87]:
from sklearn.metrics import mean_squared_error, mean_absolute_error
error = np.sqrt(mean_squared_error(y, y_pred))
print(error)

46082.71046497013


In [88]:
#Decision Tree Regressor
from sklearn.tree import DecisionTreeRegressor
decision_tree_reg = DecisionTreeRegressor(random_state=0)
decision_tree_reg.fit(X, y.values)

DecisionTreeRegressor(random_state=0)

In [89]:
y_pred = decision_tree_reg.predict(X)

In [90]:
error = np.sqrt(mean_squared_error(y, y_pred))
print("${:,.02f}".format(error))

$33,748.85


In [91]:
#Random Forest Tree
from sklearn.ensemble import RandomForestRegressor
random_forest_reg = RandomForestRegressor(random_state=0)
random_forest_reg.fit(X, y.values)

RandomForestRegressor(random_state=0)

In [92]:
y_pred = random_forest_reg.predict(X)

In [93]:
error = np.sqrt(mean_squared_error(y, y_pred))
print("${:,.02f}".format(error))

$33,818.22


In [94]:
#Using GridSearchCV
from sklearn.model_selection import GridSearchCV
max_depth = [None, 2,4,6,8,10,12]
parameters = {"max_depth": max_depth}

regressor = DecisionTreeRegressor(random_state=0)
gs = GridSearchCV(regressor, parameters, scoring='neg_mean_squared_error')
gs.fit(X, y.values)

GridSearchCV(estimator=DecisionTreeRegressor(random_state=0),
             param_grid={'max_depth': [None, 2, 4, 6, 8, 10, 12]},
             scoring='neg_mean_squared_error')

In [95]:
regressor = gs.best_estimator_

regressor.fit(X, y.values)
y_pred = regressor.predict(X)
error = np.sqrt(mean_squared_error(y, y_pred))
print("${:,.02f}".format(error))

$34,647.64


In [96]:
X

Country  EdLevel  YearsCodePro
2           16        0          23.0
3           16        0           7.0
5           15        1          21.0
6           16        1           3.0
7           16        0           3.0
...        ...      ...           ...
89156       16        0           8.0
89158       13        0           8.0
89162        1        2          24.0
89167        6        0           2.0
89170        4        2           9.0

[27716 rows x 3 columns]

In [97]:
# country, edlevel, yearscode
X = np.array([["United States of America", 'Master’s degree', 15 ]])
X

array([['United States of America', 'Master’s degree', '15']],
      dtype='<U24')

In [98]:
X[:, 0] = le_country.transform(X[:,0])
X[:, 1] = le_education.transform(X[:,1])
X = X.astype(float)
X

array([[16.,  2., 15.]])

In [99]:
y_pred = regressor.predict(X)
y_pred

c:\ProgramData\anaconda3\envs\GPU\lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but DecisionTreeRegressor was fitted with feature names
  warnings.warn(


array([171952.90990991])

In [100]:
import pickle

In [101]:
data = {"model": regressor, "le_country": le_country, "le_education": le_education}
with open('saved_steps.pkl', 'wb') as file:
    pickle.dump(data, file)

In [102]:
with open('saved_steps.pkl', 'rb') as file:
    data = pickle.load(file)

regressor_loaded = data["model"]
le_country = data["le_country"]
le_education = data["le_education"]

In [103]:
y_pred = regressor_loaded.predict(X)
y_pred

c:\ProgramData\anaconda3\envs\GPU\lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but DecisionTreeRegressor was fitted with feature names
  warnings.warn(


array([171952.90990991])